services:
  # Mock server to receive and display logs
  mock-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - tailpost-network

  # Tailpost agent
  tailpost-agent:
    build:
      context: .
      dockerfile: docker/Dockerfile.agent
    container_name: tailpost-agent
    volumes:
      - ./logs:/app/logs
      - ./config.docker.yaml:/app/config.yaml
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - LOG_LEVEL=info
      - TZ=UTC
      # 32-byte hex-encoded encryption key for AES
      - TAILPOST_ENCRYPTION_KEY=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      - MOCK_SERVER_URL=http://mock-server:8081
    depends_on:
      mock-server:
        condition: service_healthy
    networks:
      - tailpost-network

networks:
  tailpost-network:
    driver: bridge 