# Example configuration for macOS Apple System Log (ASL)
# This configuration collects logs from the macOS unified logging system

# Type of log source
log_source_type: macos_asl

# Predicate query to filter logs
# This example collects logs from kernel and system processes
macos_log_query: "process == \"kernel\" OR subsystem == \"com.apple.system\"" 

# URL to send logs to
server_url: http://log-receiver:8080/logs

# Number of log lines to batch before sending
batch_size: 20

# Maximum time to hold a batch before sending
flush_interval: 5s 