apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tailpostagents.tailpost.elastic.co
spec:
  group: tailpost.elastic.co
  names:
    kind: TailpostAgent
    listKind: TailpostAgentList
    plural: tailpostagents
    singular: tailpostagent
    shortNames:
      - tpa
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - logSources
                - serverURL
              properties:
                replicas:
                  type: integer
                  minimum: 1
                  description: Number of agent replicas to run
                image:
                  type: string
                  description: TailPost agent image to use
                imagePullPolicy:
                  type: string
                  enum:
                    - Always
                    - IfNotPresent
                    - Never
                  description: Pull policy for the agent image
                serviceAccount:
                  type: string
                  description: ServiceAccount to use for the agent
                logSources:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                    properties:
                      type:
                        type: string
                        enum:
                          - file
                          - container
                          - pod
                        description: Type of log source
                      path:
                        type: string
                        description: Path to log file (for file type)
                      containerName:
                        type: string
                        description: Container name (for container type)
                      podSelector:
                        type: object
                        description: Label selector for pods (for pod type)
                        properties:
                          matchLabels:
                            type: object
                            additionalProperties:
                              type: string
                          matchExpressions:
                            type: array
                            items:
                              type: object
                              required:
                                - key
                                - operator
                              properties:
                                key:
                                  type: string
                                operator:
                                  type: string
                                values:
                                  type: array
                                  items:
                                    type: string
                      namespaceSelector:
                        type: object
                        description: Label selector for namespaces (for pod type)
                        properties:
                          matchLabels:
                            type: object
                            additionalProperties:
                              type: string
                          matchExpressions:
                            type: array
                            items:
                              type: object
                              required:
                                - key
                                - operator
                              properties:
                                key:
                                  type: string
                                operator:
                                  type: string
                                values:
                                  type: array
                                  items:
                                    type: string
                serverURL:
                  type: string
                  description: Endpoint to send logs to
                batchSize:
                  type: integer
                  minimum: 1
                  description: Number of log lines to batch before sending
                flushInterval:
                  type: string
                  pattern: "^[0-9]+(ms|s|m|h)$"
                  description: Maximum time to hold a batch before sending
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                          pattern: "^[0-9]+m?$|^[0-9]+\\.[0-9]+$"
                        memory:
                          type: string
                          pattern: "^[0-9]+(Ki|Mi|Gi|Ti|Pi|Ei|K|M|G|T|P|E)$"
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                          pattern: "^[0-9]+m?$|^[0-9]+\\.[0-9]+$"
                        memory:
                          type: string
                          pattern: "^[0-9]+(Ki|Mi|Gi|Ti|Pi|Ei|K|M|G|T|P|E)$"
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                availableReplicas:
                  type: integer
                lastUpdateTime:
                  type: string
                  format: date-time
      subresources:
        status: {} 