apiVersion: tailpost.elastic.co/v1alpha1
kind: TailpostAgent
metadata:
  name: tailpost-sample
  namespace: default
spec:
  # Number of agent replicas
  replicas: 1
  
  # TailPost image
  image: tailpost:latest
  
  # Image pull policy
  imagePullPolicy: IfNotPresent
  
  # Service account to use
  serviceAccount: tailpost-sa
  
  # Log sources to collect
  logSources:
    # Example file source
    - type: file
      path: /var/log/syslog
    
    # Example container source
    - type: container
      containerName: nginx
      podSelector:
        matchLabels:
          app: nginx
    
    # Example pod source
    - type: pod
      podSelector:
        matchLabels:
          app: api-server
      namespaceSelector:
        matchLabels:
          environment: production
  
  # Endpoint to send logs to
  serverURL: http://log-receiver:8080/logs
  
  # Number of log lines to batch before sending
  batchSize: 20
  
  # Maximum time to hold a batch before sending
  flushInterval: 10s
  
  # Resource requirements
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi 